palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "fg:text"

[os.symbols]
# Pop = "ïŒª "
Pop = "ğŸ­"

[username]
show_always = true
style_user = "fg:text"
style_root = "fg:text"
format = '[$user ]($style)'

[directory]
style = "red"
format = "[$path ]($style)"
truncation_length = 4
truncation_symbol = "~/"

[git_branch]
symbol = "ï˜"
style = "bg:blue"
format = '[[$symbol $branch ](fg:blue)]($style)'

[git_status]
style = "bg:lavender"
format = '[[($all_status$ahead_behind )](fg:lavender)]($style)'

[c]
symbol = "î˜ "
style = "bg:green"
format = '[[$symbol( $version) ](fg:green)]($style)'

[golang]
symbol = "î˜§"
style = "bg:green"
format = '[[$symbol( $version) ](fg:green)]($style)'

[hostname]
ssh_symbol = "î¬ "
style = "bg:green"
format = '[[$symbol( $version) ](fg:green)]($style)'

[java]
symbol = "î‰– "
style = "bg:green"
format = '[[$symbol( $version) ](fg:green)]($style)'

[lua]
symbol = "î˜  "
style = "bg:green"
format = '[[$symbol( $version) ](fg:green)]($style)'

[nodejs]
symbol = "îœ˜ "
style = "bg:green"
format = '[[$symbol( $version) ](fg:green)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:green"
format = '[[$symbol( $version) ](fg:green)]($style)'

[python]
symbol = "î˜†"
style = "bg:green"
format = '[[$symbol( $version)( $virtualenv)](fg:green)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:green"
format = '[[$symbol( $version) ](fg:green)]($style)'

[character]
disabled = false
success_symbol = "[â¯](bold sapphire)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"
